PREREQS = {
    "Computer Science": [],
    "Biology": [],
    "Physics": [],
    "Chemistry": [],
    "Mathematics": []
}

Q = [
    ('COM1', 'Computer Science', 1, 'MCQ', 'Which of the following is an input device?', ['Printer', 'Speaker', 'Monitor', 'Keyboard'], 'Keyboard', 'Correct answer is Keyboard.'),
    ('COM2', 'Computer Science', 1, 'MCQ', 'What does CPU stand for?', ['Central Processing Unit', 'Control Processing Unit', 'Central Program Utility', 'Computer Personal Unit'], 'Central Processing Unit', 'Correct answer is Central Processing Unit.'),
    ('COM3', 'Computer Science', 1, 'MCQ', 'Which of the following is a high-level programming language?', ['Python', 'Machine code', 'Assembly language', 'Binary code'], 'Python', 'Correct answer is Python.'),
    ('COM4', 'Computer Science', 1, 'MCQ', 'What is the binary representation of the decimal number 5?', ['111', '110', '101', '100'], '101', 'Correct answer is 101.'),
    ('COM5', 'Computer Science', 1, 'MCQ', 'Which symbol starts a single-line comment in Python?', ['/*', '--', '//', '#'], '#', 'Correct answer is #.'),
    ('COM6', 'Computer Science', 3, 'MCQ', 'What is the time complexity of binary search on a sorted array of n elements?', ['O(n log n)', 'O(n)', 'O(log n)', 'O(1)'], 'O(log n)', 'Correct answer is O(log n).'),
    ('COM7', 'Computer Science', 3, 'MCQ', 'Which data structure follows the LIFO (Last In, First Out) principle?', ['Linked list', 'Queue', 'Stack', 'Array'], 'Stack', 'Correct answer is Stack.'),
    ('COM8', 'Computer Science', 3, 'MCQ', 'Which SQL command is used to retrieve data from a table?', ['SELECT', 'DELETE', 'INSERT', 'UPDATE'], 'SELECT', 'Correct answer is SELECT.'),
    ('COM9', 'Computer Science', 3, 'MCQ', 'In the OSI model, which layer is mainly responsible for routing packets between networks?', ['Transport layer', 'Network layer', 'Data Link layer', 'Session layer'], 'Network layer', 'Correct answer is Network layer.'),
    ('COM10', 'Computer Science', 3, 'MCQ', 'What is the output of the Python code: print(len([1, 2, [3, 4]]))?', ['5', '2', '3', '4'], '3', 'Correct answer is 3.'),
    ('COM11', 'Computer Science', 4, 'MCQ', 'What is the worst-case time complexity of Quick Sort (with a poor pivot choice)?', ['O(log n)', 'O(n^2)', 'O(n log n)', 'O(n)'], 'O(n^2)', 'Correct answer is O(n^2).'),
    ('COM12', 'Computer Science', 4, 'MCQ', 'Which of the following is NOT a necessary condition for deadlock?', ['Circular wait', 'Mutual exclusion', 'Preemption', 'Hold and wait'], 'Preemption', 'Correct answer is Preemption.'),
    ('COM13', 'Computer Science', 4, 'MCQ', 'A full binary tree (every node has 0 or 2 children) has 15 nodes. How many leaf nodes does it have?', ['8', '6', '7', '9'], '8', 'Correct answer is 8.'),
    ('COM14', 'Computer Science', 4, 'MCQ', 'Which traversal of a Binary Search Tree visits the keys in sorted (ascending) order?', ['Level-order', 'Postorder', 'Preorder', 'Inorder'], 'Inorder', 'Correct answer is Inorder.'),
    ('COM15', 'Computer Science', 4, 'MCQ', 'How many edges does a complete undirected graph with n vertices have?', ['n-1', 'n(n+1)/2', 'n^2', 'n(n-1)/2'], 'n(n-1)/2', 'Correct answer is n(n-1)/2.'),
    ('BIO16', 'Biology', 1, 'MCQ', 'Which organelle is known as the powerhouse of the cell?', ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus'], 'Mitochondria', 'Correct answer is Mitochondria.'),
    ('BIO17', 'Biology', 1, 'MCQ', 'Which pigment is mainly responsible for photosynthesis in plants?', ['Chlorophyll', 'Haemoglobin', 'Melanin', 'Keratin'], 'Chlorophyll', 'Correct answer is Chlorophyll.'),
    ('BIO18', 'Biology', 1, 'MCQ', 'Which blood vessels carry blood away from the heart?', ['Veins', 'Lymph vessels', 'Capillaries', 'Arteries'], 'Arteries', 'Correct answer is Arteries.'),
    ('BIO19', 'Biology', 1, 'MCQ', 'What is the basic structural and functional unit of life?', ['Atom', 'Organ', 'Cell', 'Tissue'], 'Cell', 'Correct answer is Cell.'),
    ('BIO20', 'Biology', 1, 'MCQ', 'Which gas do plants take in from the air for photosynthesis?', ['Nitrogen', 'Carbon dioxide', 'Oxygen', 'Hydrogen'], 'Carbon dioxide', 'Correct answer is Carbon dioxide.'),
    ('BIO21', 'Biology', 3, 'MCQ', 'Where does protein synthesis take place in the cell?', ['Lysosomes', 'Golgi apparatus', 'Ribosomes', 'Centrioles'], 'Ribosomes', 'Correct answer is Ribosomes.'),
    ('BIO22', 'Biology', 3, 'MCQ', 'In DNA, adenine pairs with which base?', ['Thymine', 'Guanine', 'Cytosine', 'Uracil'], 'Thymine', 'Correct answer is Thymine.'),
    ('BIO23', 'Biology', 3, 'MCQ', "During which phase of mitosis do chromosomes line up at the cell's equator?", ['Metaphase', 'Prophase', 'Telophase', 'Anaphase'], 'Metaphase', 'Correct answer is Metaphase.'),
    ('BIO24', 'Biology', 3, 'MCQ', 'Which blood group is considered the universal donor for red blood cells?', ['O negative', 'AB positive', 'B negative', 'A positive'], 'O negative', 'Correct answer is O negative.'),
    ('BIO25', 'Biology', 3, 'MCQ', 'Which enzyme unwinds the DNA double helix during replication?', ['Primase', 'Helicase', 'DNA ligase', 'RNA polymerase'], 'Helicase', 'Correct answer is Helicase.'),
    ('BIO26', 'Biology', 4, 'MCQ', 'What is the net gain of ATP molecules from glycolysis of one glucose molecule?', ['0', '2', '4', '36'], '2', 'Correct answer is 2.'),
    ('BIO27', 'Biology', 4, 'MCQ', 'In a cross between two heterozygous parents (Aa x Aa), what fraction of offspring show the recessive phenotype?', ['3/4', '1/2', '1/8', '1/4'], '1/4', 'Correct answer is 1/4.'),
    ('BIO28', 'Biology', 4, 'MCQ', 'Which pair of organelles contains its own circular DNA?', ['Lysosomes and peroxisomes', 'Mitochondria and chloroplasts', 'Golgi apparatus and ER', 'Ribosomes and centrioles'], 'Mitochondria and chloroplasts', 'Correct answer is Mitochondria and chloroplasts.'),
    ('BIO29', 'Biology', 4, 'MCQ', 'Okazaki fragments are formed during DNA replication on which strand?', ['The lagging strand', 'The leading strand', 'Only on RNA templates', 'Both strands equally'], 'The lagging strand', 'Correct answer is The lagging strand.'),
    ('BIO30', 'Biology', 4, 'MCQ', 'In the Krebs cycle, acetyl-CoA (2 carbons) combines with which 4-carbon compound?', ['Oxaloacetate', 'Pyruvate', 'Citrate', 'Succinate'], 'Oxaloacetate', 'Correct answer is Oxaloacetate.'),
    ('PHY31', 'Physics', 1, 'MCQ', 'What is the SI unit of force?', ['Joule', 'Newton', 'Watt', 'Pascal'], 'Newton', 'Correct answer is Newton.'),
    ('PHY32', 'Physics', 1, 'MCQ', 'What is the approximate speed of light in vacuum?', ['3 x 10^8 m/s', '3 x 10^10 m/s', '3 x 10^6 m/s', '3 x 10^5 m/s'], '3 x 10^8 m/s', 'Correct answer is 3 x 10^8 m/s.'),
    ('PHY33', 'Physics', 1, 'MCQ', 'Which of the following is a vector quantity?', ['Time', 'Mass', 'Speed', 'Velocity'], 'Velocity', 'Correct answer is Velocity.'),
    ('PHY34', 'Physics', 1, 'MCQ', '"A body stays at rest or in uniform motion unless acted on by a net force" is which law?', ["Newton's third law", "Newton's second law", "Newton's first law", 'Law of gravitation'], "Newton's first law", "Correct answer is Newton's first law."),
    ('PHY35', 'Physics', 1, 'MCQ', 'What is the SI unit of electric current?', ['Ohm', 'Volt', 'Ampere', 'Coulomb'], 'Ampere', 'Correct answer is Ampere.'),
    ('PHY36', 'Physics', 3, 'MCQ', 'A 2 kg mass accelerates at 3 m/s^2. What is the net force acting on it?', ['1.5 N', '6 N', '5 N', '9 N'], '6 N', 'Correct answer is 6 N.'),
    ('PHY37', 'Physics', 3, 'MCQ', "Which equation correctly represents Ohm's law?", ['V = IR', 'V = R/I', 'V = I + R', 'V = I/R'], 'V = IR', 'Correct answer is V = IR.'),
    ('PHY38', 'Physics', 3, 'MCQ', 'What is the kinetic energy of a 4 kg object moving at 5 m/s?', ['20 J', '50 J', '25 J', '100 J'], '50 J', 'Correct answer is 50 J.'),
    ('PHY39', 'Physics', 3, 'MCQ', 'An object is dropped from rest. Taking g = 10 m/s^2, how far does it fall in 2 seconds?', ['40 m', '10 m', '5 m', '20 m'], '20 m', 'Correct answer is 20 m.'),
    ('PHY40', 'Physics', 3, 'MCQ', 'The bending of light as it passes from one medium into another is called:', ['Reflection', 'Dispersion', 'Diffraction', 'Refraction'], 'Refraction', 'Correct answer is Refraction.'),
    ('PHY41', 'Physics', 4, 'MCQ', 'Two resistors of 6 ohm and 3 ohm are connected in parallel. What is the equivalent resistance?', ['1 ohm', '9 ohm', '2 ohm', '4.5 ohm'], '2 ohm', 'Correct answer is 2 ohm.'),
    ('PHY42', 'Physics', 4, 'MCQ', "The escape velocity from a planet's surface depends on:", ['The mass and radius of the planet only', 'The mass of the escaping object only', 'Only the temperature of the planet', 'The mass of the object and radius of the planet'], 'The mass and radius of the planet only', 'Correct answer is The mass and radius of the planet only.'),
    ('PHY43', 'Physics', 4, 'MCQ', 'In the photoelectric effect, if the frequency of incident light is increased (above threshold) at constant intensity, the maximum kinetic energy of emitted electrons:', ['Remains unchanged', 'Becomes zero', 'Increases', 'Decreases'], 'Increases', 'Correct answer is Increases.'),
    ('PHY44', 'Physics', 4, 'MCQ', 'The length of a simple pendulum is quadrupled. Its time period becomes:', ['Quadrupled', 'Doubled', 'Halved', 'Unchanged'], 'Doubled', 'Correct answer is Doubled.'),
    ('PHY45', 'Physics', 4, 'MCQ', 'An object is placed at 2F of a convex lens. The image formed is:', ['Real, inverted and magnified', 'Real, inverted and the same size', 'Real, erect and diminished', 'Virtual, erect and magnified'], 'Real, inverted and the same size', 'Correct answer is Real, inverted and the same size.'),
    ('CHE46', 'Chemistry', 1, 'MCQ', 'What is the chemical symbol for sodium?', ['N', 'S', 'Na', 'So'], 'Na', 'Correct answer is Na.'),
    ('CHE47', 'Chemistry', 1, 'MCQ', 'What is the pH of pure water at 25 °C?', ['14', '1', '7', '0'], '7', 'Correct answer is 7.'),
    ('CHE48', 'Chemistry', 1, 'MCQ', "Which gas is the most abundant in Earth's atmosphere?", ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Argon'], 'Nitrogen', 'Correct answer is Nitrogen.'),
    ('CHE49', 'Chemistry', 1, 'MCQ', 'What is the atomic number of carbon?', ['8', '6', '4', '12'], '6', 'Correct answer is 6.'),
    ('CHE50', 'Chemistry', 1, 'MCQ', 'Which of the following is a noble gas?', ['Chlorine', 'Nitrogen', 'Oxygen', 'Argon'], 'Argon', 'Correct answer is Argon.'),
    ('CHE51', 'Chemistry', 3, 'MCQ', 'How many moles are present in 36 g of water (molar mass = 18 g/mol)?', ['18 mol', '3 mol', '1 mol', '2 mol'], '2 mol', 'Correct answer is 2 mol.'),
    ('CHE52', 'Chemistry', 3, 'MCQ', 'What type of bond is present in sodium chloride (NaCl)?', ['Metallic bond', 'Covalent bond', 'Hydrogen bond', 'Ionic bond'], 'Ionic bond', 'Correct answer is Ionic bond.'),
    ('CHE53', 'Chemistry', 3, 'MCQ', 'Which of the following is a strong base?', ['NaOH', 'NH3', 'HCl', 'CH3COOH'], 'NaOH', 'Correct answer is NaOH.'),
    ('CHE54', 'Chemistry', 3, 'MCQ', 'In the reaction 2H2 + O2 gives 2H2O, how many moles of water form from 3 mol of O2 (H2 in excess)?', ['2 mol', '6 mol', '3 mol', '12 mol'], '6 mol', 'Correct answer is 6 mol.'),
    ('CHE55', 'Chemistry', 3, 'MCQ', 'What is the electronic configuration of sodium (Z = 11)?', ['2, 7, 2', '2, 8, 1', '2, 8, 2', '2, 9'], '2, 8, 1', 'Correct answer is 2, 8, 1.'),
    ('CHE56', 'Chemistry', 4, 'MCQ', 'What is the hybridisation of carbon in ethene (C2H4)?', ['sp^3d', 'sp^2', 'sp^3', 'sp'], 'sp^2', 'Correct answer is sp^2.'),
    ('CHE57', 'Chemistry', 4, 'MCQ', 'For N2 + 3H2 <=> 2NH3 (exothermic), increasing the pressure shifts the equilibrium:', ['Towards the products (NH3)', 'Towards the reactants', 'It has no effect', 'Towards N2 and H2 only'], 'Towards the products (NH3)', 'Correct answer is Towards the products (NH3).'),
    ('CHE58', 'Chemistry', 4, 'MCQ', 'What is the oxidation state of manganese in KMnO4?', ['+2', '+7', '+4', '+6'], '+7', 'Correct answer is +7.'),
    ('CHE59', 'Chemistry', 4, 'MCQ', 'How many sigma and pi bonds are present in ethyne (C2H2)?', ['4 sigma and 1 pi', '2 sigma and 3 pi', '5 sigma and 0 pi', '3 sigma and 2 pi'], '3 sigma and 2 pi', 'Correct answer is 3 sigma and 2 pi.'),
    ('CHE60', 'Chemistry', 4, 'MCQ', 'What is the pH of a 0.01 M solution of HCl (a strong acid)?', ['1', '12', '0.01', '2'], '2', 'Correct answer is 2.'),
    ('MAT61', 'Mathematics', 1, 'MCQ', 'What is 7 x 8?', ['54', '64', '48', '56'], '56', 'Correct answer is 56.'),
    ('MAT62', 'Mathematics', 1, 'MCQ', 'What is the approximate value of pi?', ['2.14', '3.14', '3.41', '4.13'], '3.14', 'Correct answer is 3.14.'),
    ('MAT63', 'Mathematics', 1, 'MCQ', 'What is the sum of the interior angles of a triangle?', ['90°', '180°', '270°', '360°'], '180°', 'Correct answer is 180°.'),
    ('MAT64', 'Mathematics', 1, 'MCQ', 'What is the square root of 144?', ['13', '12', '11', '14'], '12', 'Correct answer is 12.'),
    ('MAT65', 'Mathematics', 1, 'MCQ', 'What is 25% of 200?', ['75', '40', '50', '25'], '50', 'Correct answer is 50.'),
    ('MAT66', 'Mathematics', 3, 'MCQ', 'Solve for x: 3x + 5 = 20', ['x = 5', 'x = 6', 'x = 4', 'x = 15'], 'x = 5', 'Correct answer is x = 5.'),
    ('MAT67', 'Mathematics', 3, 'MCQ', 'What is the area of a circle of radius 7 units? (take pi = 22/7)', ['49 square units', '44 square units', '154 square units', '308 square units'], '154 square units', 'Correct answer is 154 square units.'),
    ('MAT68', 'Mathematics', 3, 'MCQ', 'What is the derivative of x^3 with respect to x?', ['x^4/4', 'x^2', '3x^2', '3x'], '3x^2', 'Correct answer is 3x^2.'),
    ('MAT69', 'Mathematics', 3, 'MCQ', 'What is the sum of the first 10 natural numbers?', ['55', '50', '100', '45'], '55', 'Correct answer is 55.'),
    ('MAT70', 'Mathematics', 3, 'MCQ', 'What are the roots of x^2 - 5x + 6 = 0?', ['2 and 3', '1 and 6', '-2 and -3', '-1 and -6'], '2 and 3', 'Correct answer is 2 and 3.'),
    ('MAT71', 'Mathematics', 4, 'MCQ', 'Evaluate the definite integral of 2x dx from x = 0 to x = 3.', ['3', '6', '9', '18'], '9', 'Correct answer is 9.'),
    ('MAT72', 'Mathematics', 4, 'MCQ', 'Two fair dice are rolled. What is the probability that the sum is 7?', ['7/36', '1/6', '1/12', '1/9'], '1/6', 'Correct answer is 1/6.'),
    ('MAT73', 'Mathematics', 4, 'MCQ', 'In how many distinct ways can the letters of the word LEVEL be arranged?', ['120', '24', '30', '60'], '30', 'Correct answer is 30.'),
    ('MAT74', 'Mathematics', 4, 'MCQ', 'What is the value of log2(64) + log3(9)?', ['12', '10', '8', '6'], '8', 'Correct answer is 8.'),
    ('MAT75', 'Mathematics', 4, 'MCQ', 'What is the determinant of the 2x2 matrix with rows (2, 3) and (1, 4)?', ['5', '11', '8', '3'], '5', 'Correct answer is 5.'),
]
